language: scala
scala:
- 2.13.5
script:
- sudo apt-get -y install fakeroot
- sbt assembly
- sbt debian:packageBin
- source ./scripts/grab_release.sh


deploy:
  provider: releases
  api_key:
    secure: "T1qaXBX1jSrO7JKlGX76vMtbgJuJFrKSKNlGGuCEco99d05OBeOuNoe+ysXDekp5kCkvAtyLwS9J37dsG1R4wj3snGnsDuK0ezCGb2PuPTkfDwGQDV8ijyBzL2FI69sUh0gMshf8ger4KA4ejJxybMk0rK57ddwztDmZHorGMo+BXlguaOP3057ujOmJIslxkQl6ac2ek/IksDmM3oHFd2OB6WdGSm8M4AwRos55mKPEH5rN7DCoL7x4fR7ynoMMy819W66Yhva8TrDSkun2lsCmpEMSp/n5LqAPYh7K4sRgL07d5VyhvfQTOzDNhzzaI1IbgQm+BtHuU7v8ZcTLrPkAyV5yAin7KmGR47pRCw54fbEwm/pvbtF8UHstMdHKZaDkg5VXCcO2DGGwRloM5AIVwNujXMU7tZTdTbXtGZZdgllEs4AJe8FQfZ0+8VTgsyzUFBGkGjuEYTpl45S3l/pTDnMyWryITlbDfSVH1ukBhDMoDGkCJMmbfaWGQPDQ39olpeR4K4vfOyDuq0EpWwfHCjHvopXlc9NTXbbmkttgA2/O5lBaJ0pnKkxx7qrHQvq55QhBwZ+NAesVrXcvbK5saZhdbNJFXfrgvzhDM/Yfn7KrGQ3P5Clx2rOr6BP8q95flk61y6FBiFwo+UGAR4NueU6DcypPlc+eEYa5YM4="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  skip_cleanup: true
  on:
    condition: $MAGURA_NEED_RELEASE = true

