language: scala

scala:
  - 2.13.5

script:
  - sudo apt-get -y install fakeroot
  - sbt assembly
  - sbt debian:packageBin
  - source ./scripts/grab_release.sh

deploy:
  provider: releases
  api_key:
    secure: "cfK4Cdtjc/uU/Z5bA/ayCJ/aEXx7nc7f59mG2LYSxOpiNiEaXioxMj5uNAuLGBvpajg4O6fxe56wvC+C5T4umM06C7erIW5g9wsuOaR0yOXmhdHDPejpOn0/rqG4OoSyJq6WxmnLgwvpm/G7YEnJSKWtXliwRCI6fcnUOOamz+8i34Y4pKphhu7rbcKrXkw5Eu/cWYeJmOyLwCLUBFjw4VSukpkD686tkvVThPPz7jYWyRewx+DWCIzhjZHfBFuNvax99j551FmkwLMRkvPhi5bguML7sjO43g1KIZV9EzkR/gCAvzfmyYQB0Ml+OqTJPX5xylSb4+48MgPXlNYkWc+UlvgAQ/3WKTV5E9yWilIQ1sSeKuPA/TeCZ9tvNcFFb/Aw6TjNed5uwHXeAU8/ps7yaYcxQ6DB16h0BAu/4YWy9mkD44AndigctlNVDfh1e3O9oiWG9CNVbI1GaazQTo0D9+faggRuuRUPGp3ECCfQPCbqWh6Hp1tFv7C3xTM0ksBcKmK+sxOJQ+85xyPrv8NZkMxcqP5fVzjymjAt60EGOnhAxn+426YxmYiNf/r0h7Yft6fjgLZJJVHOocpPnWMwG8Qz4IfFd8vRJRljNtW39yu0maPwS1YRBSsk1mrS/o1CrcHqwlcmpyfHjaFiD+7yEG3T5t1QNXu9RAtaj98="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  skip_cleanup: true
  on:
    condition: $MAGURA_NEED_RELEASE = true
