language: scala
scala:
  - 2.13.5

script:
  - sbt "run generate-release-info burbokop.magura"
  - source ./scripts/grab_release.sh
  - sudo apt-get -y install fakeroot

before_deploy:
  - sbt assembly
  - sbt debian:packageBin
  - echo $MAGURA_DEB
  - ls -l $MAGURA_DEB
  - ls

deploy:
  provider: releases
  api_key:
    secure: "XKHrjv2UaWZMbj8olKs5+V3XXOT5/Juh/tNx+JfWMSCjsvAiOGYIOt4B7YgZmJ/eqNUAEESrDYuowckvAUFBfciY/wgskLGTAv1NHDWi+wxfED25ceyqskXIR7DAAiiSyh5GjTanQ3JVWsuvys13mUGgWCU9zskL8CR7aW/1igpB9ZjIHPco7xV7qd84JCUpTsI7JOPjX6kCk3BnqLdd3OAWzzn3bPHEexSaZM+YNlmT74xnwGee94ReCHGEWbCYw8/Z9zlMi7B/wCKnA1m93V/aNuQI2WSFJvBhI0VkgK/guaRVENEZs+3rU5oNM/X9IsJrLa5fuEYoPQGsSBl2PEBnAKUZNbm7ClYYb6SocAP+TpYxbvUA/CLrKWyvdWst0061kDaOcQLCZWZl4lAtfQ17/q1y6RZ2r7Mmyi1JidTl6At6nb083WxLjdVnJJuYr5Yl491QPIwhOOj/aSqGXhWGWxFgQmZ8F4YMVgaBW9JUItnJl7DiWlpA7d6cs6JOMfEyCGSHDl1lkr9YNDHdG95fKPVDPzDY/AwikhBEt1ban+r4JQ6FSZViEWB7hEswg3vtWkRvZFqqqJ+JZpznRtwJ12e0cWhAszQ+Kb9pSKi3c/y9naZdjWeg6t7SD/SMH9GW51r1/L/wE6G9oc/6kX1H9cTjwVrG66ojQxMXHUY="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  on:
    condition: $MAGURA_NEED_RELEASE = true

