language: scala
scala:
- 2.13.5
script:
- sudo apt-get -y install fakeroot
- sbt assembly
- sbt debian:packageBin
- source ./scripts/grab_release.sh


deploy:
  provider: releases
  api_key:
    secure: "bVg1VusrSRtvToffe9FTdCIh2K+a8B3Z70TP7KTVy0uj1sqsPAogTpJWpH7byWQMMI26wDr8ps0YAsozaEMyC/mkQiX3wOcTIvzImcydff49rnEMPBfRt2rBHBo+a/ZWjEDlrO778CajzGi/K7bZN0gU2gabIxNclTfstg/P6LX/w8Ie2yFKGHisELiW7ClsTIp/sUs/QHBBqRoXYmeQYYryD7Le2qWR8AiTaNju6FbO4G0R0etTaIODGllMw2cmnGW1mIUnfmuD+vghqVC5qw3HqmSjuzjq8uUHWanXAZE30YdXStbSd4CwFlQgFDHg9IYK+Boo7Mda/VZ+HpLYJaehmbYHdEQN/6EBcyYaRUaEdNWl27BCXYMFIvYRsgxxfg+75fJvqKoflJSdfviVkDaX95k78P1CX8PGK+pYq7LLnWXmTaNOdAQTSw4WTz2SzfOPqRyn0cUqOOOyGlk9mlOdG/lQYPMNaIv5+XpCiJHRUeNmq9zKydhsFsqgcnSNsMMWxZ44pIzXcM8Xf7JFKIAPM+aPBH93KIGOAKi4oHbmzcCADvmfJw+1VMREJbvJ0k9ye5fRL5sk01cgbdIMrqEDOAVyQ5sltHgZUmSon+oIUtlQ0hzWaejIeRGW8zgFIgKxXbXma4fTFC9+ZdW3ba+CLnO7mcmet1UDsSP3JlA="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  skip_cleanup: true
  on:
    condition: $MAGURA_NEED_RELEASE = true

