language: scala

scala:
  - 2.13.5

script:
  - sudo apt-get -y install fakeroot
  - sbt assembly
  - sbt debian:packageBin
  - source ./scripts/grab_release.sh

deploy:
  provider: releases
  api_key:
    secure: "H26mw8Dz0zq2aVHvUi286tkyZB7T4IF1PlTdXKrEVEjfU1yQYzgZGbC87A1r6bBxDQzcCkobykqbUb++F71wtK42FO7ag7klL06VIzbeKF4YuoCWf9aREkPuJcfs9ex10XIQ6GzI5lQK8Z/gbBS4sC4Y8BqqIcTFOWpWEg0mHBQ4H7ObySZAv28Gc4KcKGu1QD465lu7ufm0GgMyr55HCBCp7qCaKUf922aV/JA+72ygcT8lvmS10OpXp3aRyo3DOudMElXKdHj/EN2CFi9Dx1joxGX1o0zr3h45mhqbRa0hGmVYqhrtHD1PckbAycD4SnSU1Hq7QoZg8NoTVqf8vkgIOdsjL/N+XKVDxVgkiJzBlZ4q3WMkWdxaILnyxLZm66oxM/lm8HJ20bUU/kAqlnxcUgHrKWK28I00wobteCMnd6Iml2BybpdumV+HkAcDsEOgp/YqXTZfAEw+NUmhdRX16Vb2Z0tOVou9cXEPgaHnfjqNSpycsior7oJQE8DMXQpxE7Py432YoxfXyYGMlqQ08kcJWHb/KjjFdufHA7wcytaDMRrAJSVpSxCAKYuNVRPuVaJnBZ957o9coteM9iQwnS9gBw8o1/MR/E2WRhRuStvznrYLAOCEgMGv3JIhVEeEiVKcwRulHxegqlS5v+wuvdTG8f63cjtzu3RGAbY="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  skip_cleanup: true
  on:
    condition: $MAGURA_NEED_RELEASE = true
