language: scala
scala:
- 2.13.5
script:
- sudo apt-get -y install fakeroot
- sbt assembly
- sbt debian:packageBin
- source ./scripts/grab_release.sh

deploy:
  provider: releases
  api_key:
    secure: "iJGMdUig8oll9m2bkqxvGdcOFYdYhdpN2UGUAEp0t9Is2mm5MVTA3K1Co/4IvgpxEBxg7qPYEUEnZ/0houzUhyu7rw5wzLP0THrRsg1PjFOckqj+ySLppADJo5rTtnayM3Z0zwXkHo09m6rT5GK29FkrSfJGrrxwaJ37xqX9k7hqsG/6yUSk9RtfVQrt9leH1uLN/orDjmvkTg51kpJR43KLqox97pykMd2nCVuCHAYGRE1HPcSA/F4kX6FuoRm83RK950BFINTMF1t8RiVZS2MMoChb4KM8vSImxC8XKJ2XGzoNmbEPmszdsFA/YWsCF/ltRW16KapRoqAHD2qU6SBbsm80U/IC42McGUogTTHFu5SYKsI/jKbeW/hulmCnE8zUMilxfZYZxvgBZIgaEAqDJ4G0EgVkmkGHYWqYINRw4SgfRpoRjlDepkHIi6PfVP0Y/S9tVMvWSvep5FO2MNJ6IARbKFUdgLvNbsdHQWNoWaGqjTW8Nrkt4qiN58RYUxnNsVBL0ogTnJYIcIcf57ZrzMiWXH8KliGpggzHNi987cIdfEyrF1bBXrO/Po/JeX/16VGVtkAmMWoTL3aji1vvpAZDQ8iil1C6PGbRYlcoptytx1xSxc5VjMXxcupgLxuMRtHy4YXXfB6N5sQulhY+p/tE06uk0+utgl48YAs="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  on:
    condition: $MAGURA_NEED_RELEASE = true
