language: scala
scala:
- 2.13.5
script:
- sudo apt-get -y install fakeroot
- sbt assembly
- sbt debian:packageBin
- source ./scripts/grab_release.sh

deploy:
  provider: releases
  api_key:
    secure: "EyCpkCh7216uizg12mUskeCpoXCIGyzQU9dMHPUfQHnkvyp9pkUJ59LT2X9rYzuhSacP87R7MbQY8r2ERAxsEL/mue/669UEQLmaxSUEgvNYNI3BhK98gP03G2B48RMuYwdD3hxsRZqRe4RDDfOcA7Lfldh2Sneg02tpjwi0tERYiyIJiSDOwMztevPKa0nUXvL0hGzKai+f9pC97hzyOGsqZDnik5qEeGhOAr63jXjnZ2Y+YFF0iMwSzMCaVXq3LX/EUqFnX4LMvpcoNmwTovQaI3qYgrlyBSABOFA6zKZEnvG5pr7ZgXNeq1tAnvpU38hKvta7WDvuTXAvcoeS25rRv23zvUPeazOCVomAR9wO0u1nnsoYQdWCg4H2zzuUZQYXQ8hpaBrv/wZwtEfCmUgVV1wwdOXlzA7ZsXIHaiMXidcCCeB08opxrRT/lnGxYybkvKUZDnb2Xb91TUzIWJusdAPTvQ89M+7X+UKC/TWwGfJlBWZFyizmZVHm7iDDr1jbrU42JD1R36BzSuCGXbtU8Js1jx9O3nfP9oJlvo8sPPj0qZFhRC2AhWOc7nZtjuasuBE3jtOQjufxDnS4RRAft0dc8a/7VM2q7SrXK7zjJDSWJLYRrFset+0pxhlAlvCv9aMBbwP+UxJKisdWCiy4hDR7o9LxijOlKb2nRAM="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  on:
    condition: $MAGURA_NEED_RELEASE = true
