language: scala

scala:
  - 2.13.5

script:
  - sudo apt-get -y install fakeroot
  - sbt assembly
  - sbt debian:packageBin
  - source ./scripts/grab_release.sh

deploy:
  provider: releases
  api_key:
    secure: "PwMhmsGOViC13rVYRdLergHw9CeHAYUBDcv2SGv1miGOxlTV/nWChvAVvuixKt4GnAIFCBfBp6FO7pvea/ZFxPqOuva4J3eLhN8yR/pSg4+C6IHt/v2fVeRjVMjG83s4sT5bjjgEwstslP3IOV8qCw1pxO/5xupee3QzUWbLWtSwHzBQx5OOHXkyVrkBSvh759aa6BOACBIgGqYb5qvUDTfTQR3ne8YxvVvYnskLDQ645vR+DWITkRLnf5YI1de7KjY95OfUkefV0KHFhcCLr9QJjJODtrJAtLPSLeqG7eSVK0Qlr/VqDGwTleXcmKUJFLXUx5C093HEXpC5V7drzqIyKKTpkPSxG+E5Cvk9AMwi0PM/QSL/SzYBLNLZ+ytKLhqVWBolbtC69b4OOGduLkOor+lvzTiu0HV18T9NGm2dVXW1mA/tF6BdjpkcnZNhuKj7b+Q4lmXtodOrPimgX/oQa9fKn5cQtQMXoXqveHzlRppZwp/+6lVHIp3loKzK7gpJo9qDlFuIx7PHrHIvKgHQY5see/OgXmQCybnKUrDbOCsEj/zTpWR7mby+put9s+RlwI5J8tVmmtHEjz7kjga6uSVe2e4yKtK47flqHYNN+GH1NjZ8XmC5EdTheptgBOL5Hdjba8jNjSRjZCbLier4pbMxEQvN7jKrKDZdQfc="
  file: $MAGURA_DEB
  tag_name: $MAGURA_TAG
  skip_cleanup: true
  on:
    condition: $MAGURA_NEED_RELEASE = true
